["FreeBSD network stack"]
    start = []
    add_ip_address = [
        "ifconfig {INTERFACE_PREFIX}{INTERFACE} inet {IP_ADDRESS} netmask {MASK}"
    ]
    add_static_route = [
        "route add -net {DISTANT_NETWORK} {GATEWAY}"
    ]
    stop = []

["Linux network stack"]
    start = [
        "sudo -i",
        "echo 1 > /proc/sys/net/ipv4/ip_forward"
    ]
    add_ip_address = [
        "ip link set dev {INTERFACE_PREFIX}{INTERFACE} up",
        "ip address add {IP_ADDRESS} dev {INTERFACE_PREFIX}{INTERFACE}"
    ]
    add_static_route = [
        "ip route add {DISTANT_NETWORK} via {GATEWAY}"
    ]
    stop = []

["MikroTik network stack"]
    # MikroTik CLI lines end with \r\n
    start = [
        "\r\n"
    ]
    add_ip_address = [
        "ip address add address={IP_ADDRESS} interface={INTERFACE_PREFIX}{INTERFACE}\r\n"
    ]
    add_static_route = [
        "ip route add dst-address={DISTANT_NETWORK} gateway={INTERFACE_PREFIX}{INTERFACE}\r\n"
    ]
    stop = []

["SONiC CLI"]
    start = []
    add_ip_address = [
        "sudo config interface ip add {INTERFACE_PREFIX}{INTERFACE} {IP_ADDRESS}/{NETWORK_LENGTH}"
    ]
    add_static_route = [
    ]
    stop = [
        "sleep 3",
        "sudo config interface ip remove Ethernet8 10.0.0.4/31",
        "sudo config interface ip remove Ethernet12 10.0.0.6/31",
    ]