["BIRD2"]
    start = []
    stop = []

["FRR"]
    start = [
        # SONiC only to actiave RIP
        { send = "docker exec -it bgp bash", assert_true = ["OS", "SONiC"] },
        { expect = ":/", send = "/usr/lib/frr/ripd -d", assert_true = ["OS", "SONiC"] },
        { expect = ":/", send = "/usr/lib/frr/ospfd -d", assert_true = ["OS", "SONiC"] },
        { expect = ":/", send = "exit", assert_true = ["OS", "SONiC"] },
        { send = "sleep 15", assert_true = ["OS", "SONiC"] },

        "sudo vtysh",
        { expect = "# ", send = "configure terminal" },
    ]
    RIP = {
        enable_interface = [
            { expect = "(config)# ", send = "interface {INTERFACE_PREFIX}{INTERFACE}" },
            { expect = "(config-if)# ", send = "ip rip send version 2" },
            { expect = "(config-if)# ", send = "ip rip receive version 2" },
            { expect = "(config-if)# ", send = "exit" }
        ],
        add_network = [
            { expect = "(config)# ", send = "router rip" },
            { expect = "(config-router)# ", send = "version 2" },
            { expect = "(config-router)# ", send = "network {DISTANT_NETWORK}" },
            #{ expect = "(config-router)# ", send = "redistribute connected" },
            { expect = "(config-router)# ", send = "exit" }
        ]
    }
    OSPF = {
        set_router_id = [
            { expect = "(config)# ", send = "router ospf" },
            { expect = "(config-router)# ", send = "router-id {ROUTER_ID}" },
            { expect = "(config-router)# ", send = "exit" }
        ],
        add_network = [
            { expect = "(config)# ", send = "router ospf" },
            { expect = "(config-router)# ", send = "network {DISTANT_NETWORK} area {AREA}" },
            { expect = "(config-router)# ", send = "exit" }
        ],
    }
    stop = [
        { expect = "(config)# ", send = "exit" },
        { expect = "# ", send = "write memory" },
        { expect = "# ", send = "end" },
        { expect = "# ", send = "exit" },
        { expect = "", send = "" },
    ]

["MikroTik routing stack"]
    start = []
    stop = []