["BIRD2"]
    start = [
        { send = "sysrc frr_enable=NO", assert_true = [["OS", "BSDRP-BIRD2"]] },
        { send = "sysrc bird_enable=YES", assert_true = [["OS", "BSDRP-BIRD2"]] },
        "rm /usr/local/etc/bird.conf",
        """cat <<EOF >> /usr/local/etc/bird.conf
router id {ROUTER_ID};

protocol device {
}

protocol direct {
    ipv4;
}

protocol kernel {
    ipv4 {
        import all;
        export all;
    };
}
EOF"""
    ]
    RIP = {
        start = [
            """cat <<EOF >> /usr/local/etc/bird.conf
protocol rip {
    ipv4 {
        import all;
        export all;
    };

    RIP_INTERFACES
}
EOF"""
        ],
        enable_interface = [
            "sed -i .orig 's|RIP_INTERFACES|interface \"{INTERFACE_PREFIX}{INTERFACE}\" {\\n\\t\\tversion 2;\\n\\t\\tmode multicast;\\n\\t\\tupdate time 30;\\n\\t};\\n\\tRIP_INTERFACES|' /usr/local/etc/bird.conf"
        ],
        add_network = [],
        stop = [
            "sed -i .orig 's/RIP_INTERFACES//' /usr/local/etc/bird.conf"
        ]
    }

    OSPF = {
        start = [
            """cat <<EOF >> /usr/local/etc/bird.conf
protocol ospf v2 ospf1 {
    ipv4 {
        import all;
        export all;
    };

    area 0 {
        OSPF_INTERFACES
    };
}
EOF"""
        ],
        add_area = [
            "sed -i .orig 's|OSPF_INTERFACES|interface \"{INTERFACE_PREFIX}{INTERFACE}\" {\\n\\t\\ttype broadcast;\\n\\t\\t};\\n\\t\\tOSPF_INTERFACES|' /usr/local/etc/bird.conf"
        ],
        add_network = [],
        stop = [
            "sed -i .orig 's/OSPF_INTERFACES//' /usr/local/etc/bird.conf"
        ]
    }
    BGP = {
        start = [
        """cat <<EOF >> /usr/local/etc/bird.conf
filter bgp_export {
    BGP_NETWORKS
    reject;
}

protocol bgp bgp1 {
    local as {LOCAL_AS};

    BGP_NEIGHBORS
    ipv4 {
        import all;
        export filter bgp_export;
    };
}
EOF"""
        ],
        add_neighbor = [
            "sed -i .orig 's/BGP_NEIGHBORS/neighbor {NEIGHBOR_ADDRESS} as {REMOTE_AS};\\nBGP_NEIGHBORS/' /usr/local/etc/bird.conf"
        ],
        add_network_to_advertise = [
            "sed -i .orig 's|BGP_NETWORKS|if net = {DISTANT_NETWORK} then accept;\\nBGP_NETWORKS|' /usr/local/etc/bird.conf"
        ],
        stop = [
            "sed -i .orig 's/BGP_NEIGHBORS//' /usr/local/etc/bird.conf",
            "sed -i .orig 's/BGP_NETWORKS//' /usr/local/etc/bird.conf",
        ]
}
    stop = [
        "service bird start",
        "birdc configure"
    ]

["FRR"]
    start = [
        # SONiC only
        { send = "docker exec -it bgp bash", assert_true = [["OS", "SONiC"]] },
        { expect = ":/", send = "/usr/lib/frr/ripd -d", assert_true = [["OS", "SONiC"], ["ROUTING_PROTOCOL", "RIP"]] },
        { expect = ":/", send = "/usr/lib/frr/ospfd -d", assert_true = [["OS", "SONiC"], ["ROUTING_PROTOCOL", "OSPF"]] },
        { expect = ":/", send = "exit", assert_true = [["OS", "SONiC"]] },
        { send = "sleep 15", assert_true = [["OS", "SONiC"]] },

        # BSDRP FRR
        { send = "sysrc bird_enable=NO", assert_true = [["OS", "BSDRP-FRR"]] },
        { send = "sysrc frr_enable=YES", assert_true = [["OS", "BSDRP-FRR"]] },
        { send = "sysrc frr_daemons=\"zebra ripd\"", assert_true = [["OS", "BSDRP-FRR"], ["ROUTING_PROTOCOL", "RIP"]] },
        { send = "sysrc frr_daemons=\"zebra ospfd\"", assert_true = [["OS", "BSDRP-FRR"], ["ROUTING_PROTOCOL", "OSPF"]] },
        { send = "sysrc frr_daemons=\"zebra bgpd\"", assert_true = [["OS", "BSDRP-FRR"], ["ROUTING_PROTOCOL", "BGP"]] },
        { send = "/usr/local/etc/rc.d/frr start", assert_true = [["OS", "BSDRP-FRR"]] },

        "sudo vtysh",
        { expect = "# ", send = "configure terminal" },
        { expect = "(config)# ", send = "route-map BGP-PERMIT-ALL permit 10", assert_true = [["ROUTING_PROTOCOL", "BGP"]] },
        { expect = "(config-route-map)# ", send = "exit", assert_true = [["ROUTING_PROTOCOL", "BGP"]]  },
    ]
    RIP = {
        start = [],
        enable_interface = [
            { expect = "(config)# ", send = "interface {INTERFACE_PREFIX}{INTERFACE}" },
            { expect = "(config-if)# ", send = "ip rip send version 2" },
            { expect = "(config-if)# ", send = "ip rip receive version 2" },
            { expect = "(config-if)# ", send = "exit" }
        ],
        add_network = [
            { expect = "(config)# ", send = "router rip" },
            { expect = "(config-router)# ", send = "version 2" },
            { expect = "(config-router)# ", send = "network {DISTANT_NETWORK}" },
            { expect = "(config-router)# ", send = "redistribute connected" },
            { expect = "(config-router)# ", send = "exit" }
        ],
        stop = []
    }
    OSPF = {
        start = [
            { expect = "(config)# ", send = "router ospf" },
            { expect = "(config-router)# ", send = "router-id {ROUTER_ID}" },
        ],
        add_area = [],
        add_network = [
            { expect = "(config-router)# ", send = "network {DISTANT_NETWORK} area {AREA}" },
        ],
        stop = [
            { expect = "(config-router)# ", send = "exit" }
        ]
    }
    BGP = {
        start = [
            { expect = "(config)# ", send = "router bgp {LOCAL_AS}" },
            { expect = "(config-router)# ", send = "bgp router-id {ROUTER_ID}" },
        ],
        add_neighbor = [
            { expect = "(config-router)# ", send = "neighbor {NEIGHBOR_ADDRESS} remote-as {REMOTE_AS}" },
            { expect = "(config-router)# ", send = "neighbor {NEIGHBOR_ADDRESS} route-map BGP-PERMIT-ALL in" },
            { expect = "(config-router)# ", send = "neighbor {NEIGHBOR_ADDRESS} route-map BGP-PERMIT-ALL out" },
        ],
        add_network_to_advertise = [
            { expect = "(config-router)# ", send = "network {DISTANT_NETWORK}" },
        ],
        stop = [
            { expect = "(config-router)# ", send = "exit" }
        ]
    }
    stop = [
        { expect = "(config)# ", send = "exit" },
        { expect = "# ", send = "write memory" },
        { expect = "# ", send = "end" },
        { expect = "# ", send = "exit" },
    ]

["MikroTik routing stack"]
    start = []
    RIP = {
        start = [
            "routing rip set redistribute-connected=yes\r\n"
        ],
        enable_interface = [
            "routing rip interface add interface={INTERFACE_PREFIX}{INTERFACE} receive=v2 send=v2\r\n"
        ],
        add_network = [
            "routing rip network add network={DISTANT_NETWORK}\r\n"
        ],
        stop = []
    }
    OSPF = {
        start = [
            "routing ospf instance add name=ospf-instance-1 router-id={ROUTER_ID}\r\n"
        ],
        add_area = [
            "routing ospf area add name=area{AREA} instance=ospf-instance-1 area-id={AREA}.{AREA}.{AREA}.{AREA}\r\n",
        ],
        add_network = [
            "routing ospf network add area=area{AREA} network={DISTANT_NETWORK}\r\n"
        ],
        stop = []
    }
    BGP = {
        start = [
            "routing bgp instance add name=bgp-instance-1 as={LOCAL_AS} router-id={ROUTER_ID}\r\n"
        ],
        add_neighbor = [
            "routing bgp peer add name=bgp-peer-{REMOTE_AS} instance=bgp-instance-1 remote-address={NEIGHBOR_ADDRESS} remote-as={REMOTE_AS}\r\n"
        ],
        add_network_to_advertise = [
            "ip route add dst-address={DISTANT_NETWORK} type=blackhole\r\n",
            "routing bgp network add network={DISTANT_NETWORK}\r\n",
        ],
        stop = []
    }
    stop = []