"RRUL at start" = [
    { name = "RRUL", test = "rrul", fire_at = 0, duration = 60, from = "Client", to = "Server" }
]

"VoIP at start" = [
    { name = "VoIP", test = "voip", fire_at = 0, duration = 60, from = "Client", to = "Server" },
]