[Simple]
    supported_routing_protocols = ["static", "RIP"]

    [Simple.network]
    physical_links = [
        { node_a = "Client", adapter_a = 0, node_b = "Router", adapter_b = 3 },
        { node_a = "Server", adapter_a = 0, node_b = "Router", adapter_b = 4 },
    ]

    [Simple.network.nodes.Client]
    vcpu = 2
    ram = 2048
    ip = "10.0.1.2/24"
    x = -200
    y = 0

    [Simple.network.nodes.Server]
    vcpu = 2
    ram = 2048
    ip = "10.0.2.2/24"
    x = 200
    y = 0

    [Simple.network.nodes.Router]
    number_nics = 6
    ips = { 3 = "10.0.1.1/24", 4 = "10.0.2.1/24" }
    x = 0
    y = 5
    routes_config = {
        static = [
            { distant_network = "10.0.1.0/24", gateway = "10.0.1.1", interface = 3 },
            { distant_network = "10.0.2.0/24", gateway = "10.0.2.1", interface = 4 },
        ],

        RIP = {
            interfaces_to_enable = [3, 4],
            networks_to_add = ["10.0.1.0/24", "10.0.2.0/24"]
        }
    }

[Dumbbell]
    supported_routing_protocols = ["static", "RIP"]

    [Dumbbell.network]
    physical_links = [
        { node_a = "Client", adapter_a = 0, node_b = "Router 1", adapter_b = 3 },
        { node_a = "Router 1", adapter_a = 4, node_b = "Router 2", adapter_b = 3 },
        { node_a = "Server", adapter_a = 0, node_b = "Router 2", adapter_b = 4 },
    ]

    [Dumbbell.network.nodes.Client]
    vcpu = 2
    ram = 2048
    ip = "10.0.1.2/24"
    x = -300
    y = 0

    [Dumbbell.network.nodes.Server]
    vcpu = 2
    ram = 2048
    ip = "10.0.3.2/24"
    x = 300
    y = 0

    [Dumbbell.network.nodes."Router 1"]
    number_nics = 6
    ips = { 3 = "10.0.1.1/24", 4 = "10.0.2.1/24" }
    x = -100
    y = 5
    routes_config = {
        static = [
            { distant_network = "10.0.3.0/24", gateway = "10.0.2.2", interface = 4 },
        ],

        RIP = {
            interfaces_to_enable = [3, 4],
            networks_to_add = ["10.0.1.0/24", "10.0.2.0/24"]
        }
    }

    [Dumbbell.network.nodes."Router 2"]
    number_nics = 6
    ips = { 3 = "10.0.2.2/24", 4 = "10.0.3.1/24" }
    x = 100
    y = 5
    routes_config = {
        static = [
            { distant_network = "10.0.1.0/24", gateway = "10.0.2.1", interface = 3 },
        ],

        RIP = {
            interfaces_to_enable = [3, 4],
            networks_to_add = ["10.0.2.0/24", "10.0.3.0/24"]
        }
    }