[package]
name = "NOS-GNS3-benchmark"
version = "0.1.0"
edition = "2024"
license-file = "LICENSE"

[dependencies]
tokio = { version = "1.53.1",features = ["rt", "rt-multi-thread", "macros", "time"]}
futures = "0.3.34"

pyo3 = { version = "0.29.2", features = ["auto-initialize", "anyhow", "serde", "experimental-async", "chrono"] }

serde = { version = "1.0.229", features = ["derive"] }
serde-pyobject = "0.8.0"
toml = "1.1.6"
serde_json = "1.0.151"

dotenv = "0.15.0"
rust-ini = "0.21.3"

cidr = { version = "0.3.2", features = ["serde"] }
rexpect = "0.7.1"

clap = { version = "4.6.7", features = ["derive", "color"] }
clap-verbosity-flag = { version = "3.0.4", features = ["tracing"] }

anyhow = "1.0.104"
expanduser = "1.2.2"
once_cell = "1.21.4"
strum = { version = "0.28.0", features = ["derive", "strum_macros"] }
indexmap = { version = "2.14.2", features = ["serde"] }
walkdir = "2.5.0"
uuid = { version = "1.26.1", features = ["v4"] }

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["chrono", "fmt"] }
tracing-appender = "0.2.5"